language: cpp

os:
  - linux
  - osx

homebrew:
  taps:
    - facebook/fb
  packages:
    - buck

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  - BUCK_VERSION=2019.01.10.01

before_install:
  - "./travis/before-install-$TRAVIS_OS_NAME.sh"

script:
  - buck build -c ui.superconsole=DISABLED //:buck-$BUCK_VERSION-$TRAVIS_OS_NAME
  - ./buck-out/gen/buck-$BUCK_VERSION-$TRAVIS_OS_NAME/buck-$BUCK_VERSION-$TRAVIS_OS_NAME --version

deploy:
  provider: releases
  api_key:
    secure: g68JPPUJTgr3dKtGDK8yPvt+BMnCRxSPDA9JwvUt9c5sKEp2dQM/7cUdzhnVBuvKnIW0+n0/g8B+nTiNXUOfAqKAozVAOSI+wpTbYTbAzb/rE1dPC+cRmReizsBqmMnYxkaYdmlhaJfq3O4r/nzdWBeGzUokL6vxAijRBYd8PiW4UMMz87guWL20dwtmg9eZRajBm4oqyzr+9SfaePRrO01W0ifRWqRi5mbCezdGrD3/DcayVspIqxnvyMlOU9D64px6lUDy53RQDONGnJ2Zcek2AObEZix8XVtqv4fCmug3xwXZ23IgVGnwjJ8VhxO0WuyYmKb+CMnqZh0XWEhOAGC4o6smwWeQGBSoQq/pVzNfCZaW6lk1Vz6aR++ggACoqRrZqhfWtprTV0AGf7JgNZfpcrU4ksoPUVz3BS2Z1mQwW0NxZkMSgBLKjAGMQJenRUQoGUQapUUYeYwmefG+ZtkNhMDF1fvdmQ9uvfHU14dhmrvyTYkgKI1TXQTc/8uAUSa2PYobL+vtTq+RmkbE1HCDkeYQeFG6tOGgr5EjiYWmXJ64vyWogwKWf51wiauxTZ8KwycmKfBLuHIFN48KpPjOuoiAk7CMbaK8212jkQG++Af1xkNh4VNDerACbge8wCIxhxqXxY+CDpCzA4+tRt+/IEgYoGWLsWgWmntQ528=
  file:
    - buck-out/gen/buck-$BUCK_VERSION-$TRAVIS_OS_NAME/buck-$BUCK_VERSION-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: njlr/buck-warp
    tags: true
